sensor:
  - platform: sht4x
    # SHT40 https://esphome.io/components/sensor/sht4x.html
    temperature:
      name: "Temperature Raw"
      id: temp_raw
      disabled_by_default: true
    humidity:
      name: "Humidity Raw"
      filters:
        - offset: -30
      id: humidity_raw
      disabled_by_default: true
    address: 0x44

  - platform: copy
    source_id: temp_raw
    name: "Temperature"
    id: temp
    # https://www.airgradient.com/documentation/correction-algorithms/
    # No current correction for indoor devices, but structure in place if developed

  - platform: copy
    source_id: humidity_raw
    name: "Humidity"
    id: humidity
    # https://www.airgradient.com/documentation/correction-algorithms/
    # No current correction for indoor devices, but structure in place if developed

  - platform: absolute_humidity
    name: "Humidity Absolute"
    temperature: temp_raw
    humidity: humidity_raw
    # https://esphome.io/components/sensor/absolute_humidity
    # Absolute Humidity Calculation
